name: Deploy to Lambda

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "MONGODB_URL=${{ steps.secrets.outputs.MONGODB_URL }}" >> .env
          echo "JWT_SECRET=${{ steps.secrets.outputs.JWT_SECRET }}" >> .env
          echo "SNS_AWS_ACCESS_KEY_ID=${{ steps.secrets.outputs.SNS_AWS_ACCESS_KEY_ID }}" >> .env
          echo "SNS_AWS_SECRET_ACCESS_KEY=${{ steps.secrets.outputs.SNS_AWS_SECRET_ACCESS_KEY }}" >> .env
           echo "SNS_AWS_REGION=${{ steps.secrets.outputs.SNS_AWS_REGION }}" >> .env
          echo "ALLOWED_ORIGINS=${{ steps.variables.outputs.ALLOWED_ORIGINS }}" >> .env
          echo "HASH_VERIFICATION_CODE=${{ steps.variables.outputs.HASH_VERIFICATION_CODE }}" >> .env
          echo "VERIFICATION_CODE_EXPIRE_IN_MINS=${{ steps.variables.outputs.VERIFICATION_CODE_EXPIRE_IN_MINS }}" >> .env
          echo "MAX_VERIFICATION_ATTEMPTS=${{ steps.variables.outputs.MAX_VERIFICATION_ATTEMPTS }}" >> .env
          echo "SEND_SMS=${{ steps.variables.outputs.SEND_SMS }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SNS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SNS_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.SNS_AWS_REGION }}

      - name: Update Lambda function code
          run: |
            zip -r function.zip .
            aws lambda update-function-code --function-name PhoneVerification-API --zip-file fileb://function.zip